# Generated by Django 2.0.1 on 2018-02-01 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('competition', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cosplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identity', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='C_img/')),
                ('lvl', models.CharField(
                    choices=[('N', 'Novice'), ('J', 'Journeyman'), ('M', 'Master'), ('P', 'Professional')],
                    max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LocalCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LocalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conventions', models.ManyToManyField(to='Warudo.Convention')),
                ('cosplayer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Warudo.Cosplayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cosplayer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CosplayerCity',
                                    to='Warudo.LocalCity'),
        ),
        migrations.AddField(
            model_name='cosplayer',
            name='compete',
            field=models.ManyToManyField(to='Warudo.Convention'),
        ),
        migrations.AddField(
            model_name='cosplayer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CosplayerState',
                                    to='Warudo.LocalState'),
        ),
        migrations.AddField(
            model_name='cosplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convention',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ConventionCity',
                                    to='Warudo.LocalCity'),
        ),
        migrations.AddField(
            model_name='convention',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ConventionState',
                                    to='Warudo.LocalState'),
        ),
    ]
