# Generated by Django 2.0.1 on 2018-07-24 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StreetName', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('ZipCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cosplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Expertise', models.CharField(
                    choices=[('GA', 'General'), ('Cr', 'Craftsmanship'), ('Ne', 'Needlework'), ('Ar', 'Armorer'),
                             ('Pr', 'Prop-Master')], default='GA', max_length=10)),
                ('CosUrl1', models.URLField(max_length=100)),
                ('CosUrl2', models.URLField(max_length=100)),
                ('CosUrl3', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to=settings.AUTH_USER_MODEL)),
                ('LikeCount', models.IntegerField(default=0)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Warudo.Address')),
                ('cosplayer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Warudo.Cosplayer')),
            ],
        ),
        migrations.AddField(
            model_name='cosplayer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
