# Generated by Django 2.0.1 on 2018-04-15 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('addressLine1', models.CharField(max_length=140)),
                ('addressLine2', models.CharField(blank=True, max_length=140, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('convention_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('competition',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Warudo.Contest')),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cosplayer',
            fields=[
                ('cosplayer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='assets/img')),
                ('focus', models.CharField(choices=[('Needlework', 'Needle'), ('Armoring', 'Armor'), ('Makeup', 'MaUp'),
                                                    ('Large Build', 'BigBuild')], max_length=15, null=True)),
                ('lvl', models.CharField(
                    choices=[('N', 'Novice'), ('J', 'Journeyman'), ('M', 'Master'), ('P', 'Professional')],
                    max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Warudo.Address')),
                ('conventions', models.ManyToManyField(blank=True, to='Warudo.Convention')),
                ('cosplayer',
                 models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Warudo.Cosplayer')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
